[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["suhanyujie <suhanyujie@qq.com>"]
edition = "2018"

[dependencies]
rand="0.3.14"
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
prettytable-rs = "0.10"
